prod:
  image: vizzuality/rw_dataset:1.0.0${STAGING}
  command: start
  ports:
    - '3000'
  links:
    - redis
  env_file: prod.env

  log_driver: 'gelf'
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}

worker:
  build: .
  volumes_from:
    - prod
  links:
    - redis
  env_file: prod.env

redis:
  image: redis
  container_name: redis_rw_dataset